# Generated by Django 5.1.4 on 2025-02-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-time', '-score'), 'permissions': [('can_edit', 'can edit a comment')]},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-time', '-score'), 'permissions': [('can_edit', 'can edit a story')]},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='story',
            table='stories',
        ),
    ]
