# Generated by Django 5.1.4 on 2025-03-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='story',
            table='story',
        ),
    ]
