# Generated by Django 5.1.4 on 2025-03-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='story',
            table='stories',
        ),
    ]
