# Generated by Django 5.1.4 on 2025-02-16 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('dead', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'Pollopt')], max_length=10)),
                ('text', models.TextField(default='')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('descendants', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(max_length=255)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-time', '-score'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('dead', models.BooleanField(blank=True, default=False)),
                ('type', models.CharField(choices=[('job', 'Job'), ('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('pollopt', 'Pollopt')], max_length=10)),
                ('text', models.TextField(default='')),
                ('score', models.IntegerField(blank=True, default=0)),
                ('descendants', models.IntegerField(blank=True, default=0)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='poll.poll')),
            ],
            options={
                'ordering': ('-time', '-score'),
                'abstract': False,
            },
        ),
    ]
