# Generated by Django 5.1.4 on 2025-02-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-time', '-score'), 'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ('-time', '-score'), 'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
