# Generated by Django 5.1.4 on 2025-02-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_poll_options_alter_polloption_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-time', '-score')},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ('-time', '-score')},
        ),
    ]
