# Generated by Django 5.1.4 on 2025-02-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_poll_options_alter_polloption_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-time', '-score'), 'permissions': [('can_edit', 'can edit poll')]},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'ordering': ('-time', '-score'), 'permissions': [('can_edit', 'can edit poll option')]},
        ),
        migrations.AlterModelTable(
            name='poll',
            table='polls',
        ),
        migrations.AlterModelTable(
            name='polloption',
            table='polloptions',
        ),
    ]
