# Generated by Django 5.1.4 on 2025-02-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-time', '-score'), 'permissions': [('can_edit', 'can edit job posting')]},
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
